KS-1-3 Gagarin's takeoff and landing
ElKalinin/KotlinSprint pull request #3
Opened 2024-09-16 20:49 UTC by ElKalinin

2024-09-17 13:42 UTC, ievetrovdev requested changes

2024-09-17 13:42 UTC, ievetrovdev commented on src/main/kotlin/lesson_1/lesson1_task3.kt
> +    println(year);
Рекомендую отделять блок с определением переменных от всего остального кода пустой строкой. Код будет выглядеть менее монолитным, что кратно повысит читаемость.

2024-09-17 13:42 UTC, ievetrovdev commented on src/main/kotlin/lesson_1/lesson1_task3.kt
> +    val year = 1961;
В Kotlin, как в Java, не требуется указывать точку с запятой, давай почистим

2024-09-17 19:02 UTC, ElKalinin commented
Добавил новый коммит с исправлениями!

2024-09-18 18:29 UTC, ievetrovdev approved these changes

2024-09-18 21:37 UTC, merged