KS-1-4 fight characteristics output
ElKalinin/KotlinSprint pull request #4
Opened 2024-09-16 21:06 UTC by ElKalinin

2024-09-17 13:44 UTC, ievetrovdev requested changes
По задаче все огонь, но давай доведем до идеала)

2024-09-17 13:44 UTC, ievetrovdev commented on src/main/kotlin/lesson_1/lesson1_task4.kt
> +    println(length);
Рекомендую блок с объявлением переменных отделять пустой строкой от всего остального кода. Так код будет менее монолитным, что улучшить читабельность.

2024-09-17 13:44 UTC, ievetrovdev commented on src/main/kotlin/lesson_1/lesson1_task4.kt
> +    val age: Byte = 27;
Указывать точку с запятой, как в Java не нужно, давай почистим)

2024-09-17 19:08 UTC, ElKalinin commented
Внёс правки!

2024-09-18 18:33 UTC, ievetrovdev approved these changes
Теперь этот пулл реквест можно мержить в мастер. Перед созданием новой ветки (обязательно из мастера) не забудь сделать его Update, чтобы слитые изменения прилетели с сервера в локальный проект.

2024-09-18 21:38 UTC, merged