KS-1-5 convert seconds to hours and minutes
ElKalinin/KotlinSprint pull request #5
Opened 2024-09-17 20:08 UTC by ElKalinin

2024-09-18 18:38 UTC, ievetrovdev requested changes

2024-09-18 18:38 UTC, ievetrovdev commented on src/main/kotlin/lesson_1/lesson1_task5.kt
> +    val numberOfSeconds = 5409
Количество секунд, проведенных Гагариным в космосе было в прошлой задаче: 6480 
Давай исправим

2024-09-18 18:38 UTC, ievetrovdev commented on src/main/kotlin/lesson_1/lesson1_task5.kt
> +    print('0')
Так как это 5 задача ("со звездочкой") не по уровню урока, то предлагаю использовать более элегантное решение). (может потребовать дополнительного ресерча). Для корректного вывода нуля вначале попробуй посмотреть в сторону String.format().

2024-09-18 18:38 UTC, ievetrovdev commented on src/main/kotlin/lesson_1/lesson1_task5.kt
> +    val second = numberOfSeconds % 60
Чтобы снизить риск ошибок, предлагаю еще вынести 60 в константу. Кроме того это [магическое число](https://ru.wikipedia.org/wiki/%D0%9C%D0%B0%D0%B3%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%BE%D0%B5_%D1%87%D0%B8%D1%81%D0%BB%D0%BE_(%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5)#%D0%9F%D0%BB%D0%BE%D1%85%D0%B0%D1%8F_%D0%BF%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D0%BA%D0%B0_%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F), что тоже не является хорошей практикой.

2024-09-18 18:38 UTC, ievetrovdev commented on src/main/kotlin/lesson_1/lesson1_task5.kt
> +    val hour = numberOfSeconds / 3600
Неизвестно откуда взялось это число. Все должно высчитываться программно.

2024-09-20 09:46 UTC, ievetrovdev requested changes

2024-09-20 09:46 UTC, ievetrovdev commented on src/main/kotlin/lesson_1/lesson1_task5.kt
> +    println(String.format("%02d", second))
Отлично!) можно даже еще аккуратнее сделать
`println("%02d:%02d:%02d".format(hours, minutes, second))`

2024-09-20 09:54 UTC, ElKalinin commented on src/main/kotlin/lesson_1/lesson1_task5.kt
> +    println(String.format("%02d", second))
Круто, спасибо!

2024-09-21 10:16 UTC, ievetrovdev approved these changes

2024-09-21 12:44 UTC, merged